version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./chat_api/Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - ./diabetes/diabetes/models:/app/diabetes/models
