route:
  group_by: ['alertname', 'job']

  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

  receiver: discord

receivers:
- name: discord
  discord_configs:
  - webhook_url: https://discord.com/api/webhooks/1131241192202444861/dlE3gpiSxAAEbMFEvZcFFv0Dv-GHga1G4xrToKYjKe-eEs87Bl6BOEFD03971yviIKXP
