apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: diabetes
  labels:
    app: diabetes
    namespace: model-serving
spec:
  selector:
    matchLabels:
      app: diabetes
  namespaceSelector:
    any: true
  endpoints:
  - port: web
    path: /prometheus
    interval: 10s